import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { readFile } from "node:fs/promises";
import { fileURLToPath, pathToFileURL } from "node:url";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// Embed the KaTeX stylesheet and woff2 fonts in main.js so exported HTML
// remains readable without a network connection or extra release assets.
const katexCss = {
	name: "inline-katex-css",
	setup(build) {
		build.onResolve({ filter: /^katex\/dist\/katex\.min\.css\?inline$/ }, () => ({
			path: fileURLToPath(import.meta.resolve("katex/dist/katex.min.css")),
			namespace: "katex-inline",
		}));
		build.onLoad({ filter: /.*/, namespace: "katex-inline" }, async ({ path }) => {
			let css = await readFile(path, "utf8");
			css = css.replace(/,url\(fonts\/[^)]+\) format\("(?:woff|truetype)"\)/g, "");
			const fontNames = [...new Set(css.match(/fonts\/[\w-]+\.woff2/g) ?? [])];
			const watchFiles = [path];
			for (const name of fontNames) {
				const fontPath = fileURLToPath(new URL(name, pathToFileURL(path)));
				const font = await readFile(fontPath);
				watchFiles.push(fontPath);
				css = css.replaceAll(name, `data:font/woff2;base64,${font.toString("base64")}`);
			}
			return {
				contents: `export default ${JSON.stringify(css)}`,
				loader: "js",
				watchFiles,
			};
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	plugins: [katexCss],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2021",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
